-- DATA PREPARATION AND UNDERSTANDING 

select * from Customer 
select * from prod_cat_info 
select * from Transactions 

--Q1 What is the total number of rows in each of the 3 tables in the database?

select count(*) as Rows from Customer 
select count(*) as Rows from prod_cat_info  
select count(*) as Rows from Transactions 

--Q2 What is the total number of transactions that have a return?

SELECT COUNT(total_amt) as Transactions_having_return from Transactions
where total_amt like '-%'

--Q3 The dates are not in correct format .Convert the date variables into valid date formats before proceeding ahead.

select convert(date,DOB,105) as 'DATE' from Customer
select convert(date,tran_date,105) as 'DATE' from Transactions

--Q4 What is the time range of the Trasaction data avaliable for analysis? Show the output in the number of days,months and years simultaneously in different columns.

select DATEDIFF(DAY,min(convert(date,tran_date,105)),max(convert(date,tran_date,105))) as Day,
datediff(month,min(convert(date,tran_date,105)),max(convert(date,tran_date,105))) AS MONTH,
datediff(year,min(convert(date,tran_date,105)),max(convert(date,tran_date,105))) AS YEAR 
from Transactions

--Q5 Which product category does the sub category "DIY" belong to ?

select prod_cat from prod_cat_info where prod_subcat like 'DIY'

--DATA ANALYSIS
--Q1 Which channel is most frequently used for transaction?

select  top 1 Store_type,count(transaction_id) as count_ 
from Transactions
group by Store_type
order by count(transaction_id) desc

--Q2 What is the count of Male and Female customers in the database?

select Gender,count(customer_id) as Count_of_gender from Customer
where Gender in ('M','F')
group by gender

--Q3 From which city do we have maximum number of customers and how many ?

select top 1 city_code, count(customer_id) as Count_of_Customer
from Customer
group by city_code
order by Count_of_Customer desc

--Q4  How many sub-categories are there under the Books category?

select count(prod_subcat) as SUB_CAT_Count 
from prod_cat_info
where prod_cat like 'BOOKS'


--Q5 What is the maximum quantity of product ever ordered ?

select top 1 Qty from Transactions
order by Qty desc

--Q6 What is the net total revenue generated in categories Electronics and Books?

SELECT SUM(TOTAL_AMT) as Amount
FROM TRANSACTIONs as trans
INNER JOIN PROD_CAT_INFO as PC ON trans.prod_cat_code = PC.prod_cat_code
AND trans.prod_subcat_code = PC.prod_sub_cat_code
WHERE PROD_CAT in ('BOOKS','ELECTRONICS') 


--Q7 How many customer have >10 transaction with us , excluding retuns ?

select count(customer_Id) as Customer_count
from Customer where customer_Id in 
(
select cust_id
from Transactions
Inner join Customer on customer_Id = cust_id
where total_amt not like '-%'
group by cust_id having count(transaction_id) >10
)

--Q8 What is the combined revenue earned from the "Electronins" and "Clothing" categories, from "Flagship store" ?

SELECT SUM(TOTAL_AMT) AS Amount FROM TRANSACTIONS as Trans
INNER JOIN prod_cat_info PC ON Trans.PROD_CAT_CODE = PC.PROD_CAT_CODE 
	  AND trans.prod_subcat_code = PC.prod_sub_cat_code
WHERE PROD_CAT IN ('CLOTHING','ELECTRONICS') AND STORE_TYPE = 'FLAGSHIP STORE'

--Q9 What is the total revenue generated from "Male" customers in "Electronics" category ? Output should display total revenue by prod sub-cat.

SELECT prod_subcat, SUM(TOTAL_AMT) as Revenue
FROM Transactions as trans
Inner JOIN CUSTOMER ON CUSTOMER_ID=CUST_ID
Inner join prod_cat_info as PC ON prod_sub_cat_code = PROD_SUBCAT_CODE AND trans.prod_cat_code = PC.PROD_CAT_CODE
WHERE PC.PROD_CAT_CODE= '3' AND GENDER = 'M'
GROUP BY PROD_SUBCAT


--Q10 What is percentage of sales and returns by product sub category, display only top 5 sub categories in terms of sales?

;WITH SalesData AS (
    SELECT
        prod_subcat,
        SUM(CASE WHEN total_amt >= 0 THEN total_amt  END) AS TotalSales,
        SUM(CASE WHEN total_amt < 0 THEN abs(total_amt) END) AS TotalReturns
    FROM
        Transactions
		inner join prod_cat_info on prod_cat_info.prod_cat_code=Transactions.prod_cat_code and Transactions.prod_subcat_code=prod_cat_info.prod_sub_cat_code
    GROUP BY
        prod_subcat
),
TopSubCategories AS (
    SELECT TOP 5
        prod_subcat,
        TotalSales,
        TotalReturns,
        (CAST(TotalSales AS FLOAT) / (SUM(TotalSales) OVER())) * 100 AS PercentageOfTotalSales,
        (CAST(TotalReturns AS FLOAT) / (SUM(TotalReturns) OVER())) * 100 AS PercentageOfTotalReturns
    FROM
        SalesData
    ORDER BY
        TotalSales DESC
)
SELECT
    prod_subcat,
    TotalSales,
    TotalReturns,
    PercentageOfTotalSales,
    PercentageOfTotalReturns
FROM
    TopSubCategories;

 --Q11 For all customers aged between 25 to 35 years find what is the net total revenue generated by these consumers in the last 30 days of transactions from max transaction date avaliable in the data ?

SELECT CUST_ID,SUM(TOTAL_AMT) AS NET_TOTAL_REVENUE FROM TRANSACTIONs
WHERE CUST_ID IN 
(SELECT CUSTOMER_ID
FROM CUSTOMER
WHERE DATEDIFF(YEAR,CONVERT(DATE,DOB,103),GETDATE()) BETWEEN 25 AND 35)
AND CONVERT(DATE,tran_date,103) BETWEEN DATEADD(DAY,-30,(SELECT MAX(CONVERT(DATE,tran_date,103)) FROM Transactions)) 
AND (SELECT MAX(CONVERT(DATE,tran_date,103)) FROM TRANSACTIONs)
GROUP BY CUST_ID


--Q12 Which product category has seen the max value of retuns in the last 3 months of transaction?

select top 1 prod_cat,Sum(total_amt) as Value_of_returns from Transactions as A
Inner join prod_cat_info B on A.prod_cat_code=B.prod_cat_code and A.prod_subcat_code=B.prod_sub_cat_code 
where total_amt<0 and convert(date,tran_date,103) between DATEADD(month,-3,(select max(convert(date,tran_date,103)) from Transactions)) 
and (select max(convert(date,tran_date,103))  from Transactions) 
group by prod_cat 
order by Sum(total_amt) DESC 

--Q13 Which store-type sells the maximum products, by value of sales amount and by quantity sold ?


  with A as (SELECT TOP 1 Store_Type, SUM(total_amt) AS TotalSalesAmount
     FROM Transactions
	 where total_amt >0
     GROUP BY Store_type
     ORDER BY SUM(total_amt) DESC),
  B as (SELECT TOP 1 Store_type, SUM(Qty) AS TotalQuantitySold
     FROM Transactions
	 where Qty>0 
     GROUP BY Store_type
     ORDER BY SUM(Qty) DESC)
	 select A.Store_type,TotalSalesAmount,TotalQuantitySold from A
	 inner join B on  B.Store_type=A.Store_type

--Q14 What are the categories for which average revenue is above the overall average.

select prod_cat,AVG( case when total_amt>0 then total_amt end) as Average_revenue from Transactions
inner join prod_cat_info on prod_cat_info.prod_cat_code=Transactions.prod_cat_code and Transactions.prod_subcat_code=prod_cat_info.prod_sub_cat_code
group by prod_cat
having AVG(total_amt) > (select AVG(total_amt) from Transactions)

--Q15 Fing the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold.

SELECT PROD_CAT, PROD_SUBCAT, AVG(TOTAL_AMT) AS Average_Revenue, SUM(TOTAL_AMT) AS Revenue
FROM transactions as trans
INNER JOIN prod_cat_info as PC ON trans.prod_cat_code=PC.prod_cat_code AND prod_sub_cat_code=PROD_SUBCAT_CODE
WHERE total_amt>0 and PROD_CAT IN
(
SELECT TOP 5 
PROD_CAT
FROM transactions 
INNER JOIN prod_cat_info ON trans.prod_cat_code= PC.prod_cat_code AND prod_sub_cat_code = PROD_SUBCAT_CODE
GROUP BY PROD_CAT
ORDER BY SUM(case when QTY>0 then Qty end) DESC
)
GROUP BY PROD_CAT, PROD_SUBCAT 



